## <u> Use only those concepts which have been taught till now </u>

# <b> Problem 1: Import Pandas and Numpy in the notebook </b>

In [ ]:
# Import statements
import pandas as pd
import numpy as np

# <b> Problem 2 : Load the automobile_data.csv kept in the shared folder

In [ ]:
# Mount your drive and read the csv file. Make sure you are using the correct file path

data=pd.read_csv("automobile_data.csv")

# <b> Problem 3 : Do a basic inspection and print the first and last 15 rows of your dataframe

In [ ]:
# Your code here
print(data.iloc[:15])
print(data.iloc[-15:])

    symboling normalized-losses         make fuel-type aspiration  \
0           3                 ?  alfa-romero       gas        std
1           3                 ?  alfa-romero       gas        std
2           1                 ?  alfa-romero       gas        std
3           2               164         audi       gas        std
4           2               164         audi       gas        std
5           2                 ?         audi       gas        std
6           1               158         audi       gas        std
7           1                 ?         audi       gas        std
8           1               158         audi       gas      turbo
9           0                 ?         audi       gas      turbo
10          2               192          bmw       gas        std
11          0               192          bmw       gas        std
12          0               188          bmw       gas        std
13          0               188          bmw       gas        std
14          1                 ?          bmw       gas        std

   num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0           two  convertible          rwd           front        88.6  ...
1           two  convertible          rwd           front        88.6  ...
2           two    hatchback          rwd           front        94.5  ...
3          four        sedan          fwd           front        99.8  ...
4          four        sedan          4wd           front        99.4  ...
5           two        sedan          fwd           front        99.8  ...
6          four        sedan          fwd           front       105.8  ...
7          four        wagon          fwd           front       105.8  ...
8          four        sedan          fwd           front       105.8  ...
9           two    hatchback          4wd           front        99.5  ...
10          two        sedan          rwd           front       101.2  ...
11         four        sedan          rwd           front       101.2  ...
12          two        sedan          rwd           front       101.2  ...
13         four        sedan          rwd           front       101.2  ...
14         four        sedan          rwd           front       103.5  ...

    engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0           130         mpfi  3.47    2.68               9.0        111
1           130         mpfi  3.47    2.68               9.0        111
2           152         mpfi  2.68    3.47               9.0        154
3           109         mpfi  3.19     3.4              10.0        102
4           136         mpfi  3.19     3.4               8.0        115
5           136         mpfi  3.19     3.4               8.5        110
6           136         mpfi  3.19     3.4               8.5        110
7           136         mpfi  3.19     3.4               8.5        110
8           131         mpfi  3.13     3.4               8.3        140
9           131         mpfi  3.13     3.4               7.0        160
10          108         mpfi   3.5     2.8               8.8        101
11          108         mpfi   3.5     2.8               8.8        101
12          164         mpfi  3.31    3.19               9.0        121
13          164         mpfi  3.31    3.19               9.0        121
14          164         mpfi  3.31    3.19               9.0        121

    peak-rpm city-mpg highway-mpg  price
0       5000       21          27  13495
1       5000       21          27  16500
2       5000       19          26  16500
3       5500       24          30  13950
4       5500       18          22  17450
5       5500       19          25  15250
6       5500       19          25  17710
7       5500       19          25  18920
8       5500       17          20  23875
9       5500       16          22      ?
10      5800       23          29  16430
11      5800       23          29  16925
12      4250       21          28  20970
13      4250       21          28  21105
14      4250       20          25  24565

[15 rows x 26 columns]
     symboling normalized-losses        make fuel-type aspiration  \
190          3               256  volkswagen       gas        std
191          0                 ?  volkswagen       gas        std
192          0                 ?  volkswagen    diesel      turbo
193          0                 ?  volkswagen       gas        std
194         -2               103       volvo       gas        std
195         -1                74       volvo       gas        std
196         -2               103       volvo       gas        std
197         -1                74       volvo       gas        std
198         -2               103       volvo       gas      turbo
199         -1                74       volvo       gas      turbo
200         -1                95       volvo       gas        std
201         -1                95       volvo       gas      turbo
202         -1                95       volvo       gas        std
203         -1                95       volvo    diesel      turbo
204         -1                95       volvo       gas      turbo

    num-of-doors body-style drive-wheels engine-location  wheel-base  ...  \
190          two  hatchback          fwd           front        94.5  ...
191         four      sedan          fwd           front       100.4  ...
192         four      sedan          fwd           front       100.4  ...
193         four      wagon          fwd           front       100.4  ...
194         four      sedan          rwd           front       104.3  ...
195         four      wagon          rwd           front       104.3  ...
196         four      sedan          rwd           front       104.3  ...
197         four      wagon          rwd           front       104.3  ...
198         four      sedan          rwd           front       104.3  ...
199         four      wagon          rwd           front       104.3  ...
200         four      sedan          rwd           front       109.1  ...
201         four      sedan          rwd           front       109.1  ...
202         four      sedan          rwd           front       109.1  ...
203         four      sedan          rwd           front       109.1  ...
204         four      sedan          rwd           front       109.1  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
190          109         mpfi  3.19     3.4               8.5         90
191          136         mpfi  3.19     3.4               8.5        110
192           97          idi  3.01     3.4              23.0         68
193          109         mpfi  3.19     3.4               9.0         88
194          141         mpfi  3.78    3.15               9.5        114
195          141         mpfi  3.78    3.15               9.5        114
196          141         mpfi  3.78    3.15               9.5        114
197          141         mpfi  3.78    3.15               9.5        114
198          130         mpfi  3.62    3.15               7.5        162
199          130         mpfi  3.62    3.15               7.5        162
200          141         mpfi  3.78    3.15               9.5        114
201          141         mpfi  3.78    3.15               8.7        160
202          173         mpfi  3.58    2.87               8.8        134
203          145          idi  3.01     3.4              23.0        106
204          141         mpfi  3.78    3.15               9.5        114

     peak-rpm city-mpg highway-mpg  price
190      5500       24          29   9980
191      5500       19          24  13295
192      4500       33          38  13845
193      5500       25          31  12290
194      5400       23          28  12940
195      5400       23          28  13415
196      5400       24          28  15985
197      5400       24          28  16515
198      5100       17          22  18420
199      5100       17          22  18950
200      5400       23          28  16845
201      5300       19          25  19045
202      5500       18          23  21485
203      4800       26          27  22470
204      5400       19          25  22625

[15 rows x 26 columns]

# <b>Problem 4 : You need to clean the data a little bit now. Replace all column values with the values <code>?</code> and <code>n.a</code> with <code>NaN</code>

In [ ]:
# Your code here
data.replace(["?","n.a"],np.nan, inplace=True)

In [ ]:
print(data.isnull().sum())

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [ ]:
numeric_columns = ['normalized-losses', 'bore', 'stroke', 'horsepower', 'peak-rpm', 'price']
data[numeric_columns] = data[numeric_columns].astype(float)

In [ ]:

data['price'] = data['price'].astype(float)

# <b>Problem 5 : Print the company name which manufactured the most expensive car. Also print the price of the most expensive car

In [ ]:
# Your code here
highest = np.argmax(data["price"])
high_price=data.loc[highest,"price"]
high_make=data.loc[highest,"make"]
print(high_price,high_make)

45400.0 mercedes-benz

# <b>Problem 6 : Calculate maximum horsepowers for each company. </b>

In [ ]:
# Your code here
max_power=data.groupby("make")["horsepower"].max()
print(max_power)

make
alfa-romero      154.0
audi             160.0
bmw              182.0
chevrolet         70.0
dodge            145.0
honda            101.0
isuzu             90.0
jaguar           262.0
mazda            135.0
mercedes-benz    184.0
mercury          175.0
mitsubishi       145.0
nissan           200.0
peugot           142.0
plymouth         145.0
porsche          288.0
renault            NaN
saab             160.0
subaru           111.0
toyota           161.0
volkswagen       110.0
volvo            162.0
Name: horsepower, dtype: float64

# <b> Problem 7 : Print the total number of cars manufactured by each company

In [ ]:
# Your code here
total_car_bycomp=data["make"].value_counts()
print(total_car_bycomp)

make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
jaguar            3
chevrolet         3
alfa-romero       3
renault           2
mercury           1
Name: count, dtype: int64

# <b> Problem 8 : Create a new column for the updated price. This updated price will be calculated on top of the given price - if the engine is in front, price will be same else if the engine is in rear, price will be doubled </b>

In [ ]:
# Your code here. Use apply and lambda
def updated_price(row):
    if row['engine-location'] == 'front':
        return row['price']
    elif row['engine-location'] == 'rear':
        return row['price'] * 2

data['updated_price']=data.apply(updated_price,axis=1)
print(data)

     symboling  normalized-losses         make fuel-type aspiration  \
0            3                NaN  alfa-romero       gas        std
1            3                NaN  alfa-romero       gas        std
2            1                NaN  alfa-romero       gas        std
3            2              164.0         audi       gas        std
4            2              164.0         audi       gas        std
..         ...                ...          ...       ...        ...
200         -1               95.0        volvo       gas        std
201         -1               95.0        volvo       gas      turbo
202         -1               95.0        volvo       gas        std
203         -1               95.0        volvo    diesel      turbo
204         -1               95.0        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     fuel-system  bore  stroke  compression-ratio horsepower peak-rpm  \
0           mpfi  3.47    2.68                9.0      111.0   5000.0
1           mpfi  3.47    2.68                9.0      111.0   5000.0
2           mpfi  2.68    3.47                9.0      154.0   5000.0
3           mpfi  3.19    3.40               10.0      102.0   5500.0
4           mpfi  3.19    3.40                8.0      115.0   5500.0
..           ...   ...     ...                ...        ...      ...
200         mpfi  3.78    3.15                9.5      114.0   5400.0
201         mpfi  3.78    3.15                8.7      160.0   5300.0
202         mpfi  3.58    2.87                8.8      134.0   5500.0
203          idi  3.01    3.40               23.0      106.0   4800.0
204         mpfi  3.78    3.15                9.5      114.0   5400.0

     city-mpg highway-mpg    price  updated_price
0          21          27  13495.0        13495.0
1          21          27  16500.0        16500.0
2          19          26  16500.0        16500.0
3          24          30  13950.0        13950.0
4          18          22  17450.0        17450.0
..        ...         ...      ...            ...
200        23          28  16845.0        16845.0
201        19          25  19045.0        19045.0
202        18          23  21485.0        21485.0
203        26          27  22470.0        22470.0
204        19          25  22625.0        22625.0

[205 rows x 27 columns]

# <b>Problem 9 : Sort the dataframe by car and price columns

In [ ]:
# Your code here
cars_data = data.sort_values(by=['make', 'price'])
print(cars_data)

     symboling  normalized-losses         make fuel-type aspiration  \
0            3                NaN  alfa-romero       gas        std
1            3                NaN  alfa-romero       gas        std
2            1                NaN  alfa-romero       gas        std
3            2              164.0         audi       gas        std
5            2                NaN         audi       gas        std
..         ...                ...          ...       ...        ...
199         -1               74.0        volvo       gas      turbo
201         -1               95.0        volvo       gas      turbo
202         -1               95.0        volvo       gas        std
203         -1               95.0        volvo    diesel      turbo
204         -1               95.0        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
5            two        sedan          fwd           front        99.8  ...
..           ...          ...          ...             ...         ...  ...
199         four        wagon          rwd           front       104.3  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     fuel-system  bore  stroke  compression-ratio horsepower peak-rpm  \
0           mpfi  3.47    2.68                9.0      111.0   5000.0
1           mpfi  3.47    2.68                9.0      111.0   5000.0
2           mpfi  2.68    3.47                9.0      154.0   5000.0
3           mpfi  3.19    3.40               10.0      102.0   5500.0
5           mpfi  3.19    3.40                8.5      110.0   5500.0
..           ...   ...     ...                ...        ...      ...
199         mpfi  3.62    3.15                7.5      162.0   5100.0
201         mpfi  3.78    3.15                8.7      160.0   5300.0
202         mpfi  3.58    2.87                8.8      134.0   5500.0
203          idi  3.01    3.40               23.0      106.0   4800.0
204         mpfi  3.78    3.15                9.5      114.0   5400.0

     city-mpg highway-mpg    price  updated_price
0          21          27  13495.0        13495.0
1          21          27  16500.0        16500.0
2          19          26  16500.0        16500.0
3          24          30  13950.0        13950.0
5          19          25  15250.0        15250.0
..        ...         ...      ...            ...
199        17          22  18950.0        18950.0
201        19          25  19045.0        19045.0
202        18          23  21485.0        21485.0
203        26          27  22470.0        22470.0
204        19          25  22625.0        22625.0

[205 rows x 27 columns]

# <b> Problem 10 : Create a new column which stores the number of doors in a car as integers.

In [ ]:
# Your code here. Use apply
def con_num_of_doors(row):
    if row['num-of-doors'] == 'four':
        return 4
    elif row['num-of-doors'] == 'two':
        return 2
    else:
        return None

data['num-doors-int'] = data.apply(con_num_of_doors, axis=1)

print(data)

     symboling  normalized-losses         make fuel-type aspiration  \
0            3                NaN  alfa-romero       gas        std
1            3                NaN  alfa-romero       gas        std
2            1                NaN  alfa-romero       gas        std
3            2              164.0         audi       gas        std
4            2              164.0         audi       gas        std
..         ...                ...          ...       ...        ...
200         -1               95.0        volvo       gas        std
201         -1               95.0        volvo       gas      turbo
202         -1               95.0        volvo       gas        std
203         -1               95.0        volvo    diesel      turbo
204         -1               95.0        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     bore  stroke  compression-ratio  horsepower peak-rpm city-mpg  \
0    3.47    2.68                9.0       111.0   5000.0       21
1    3.47    2.68                9.0       111.0   5000.0       21
2    2.68    3.47                9.0       154.0   5000.0       19
3    3.19    3.40               10.0       102.0   5500.0       24
4    3.19    3.40                8.0       115.0   5500.0       18
..    ...     ...                ...         ...      ...      ...
200  3.78    3.15                9.5       114.0   5400.0       23
201  3.78    3.15                8.7       160.0   5300.0       19
202  3.58    2.87                8.8       134.0   5500.0       18
203  3.01    3.40               23.0       106.0   4800.0       26
204  3.78    3.15                9.5       114.0   5400.0       19

     highway-mpg    price  updated_price  num-doors-int
0             27  13495.0        13495.0            2.0
1             27  16500.0        16500.0            2.0
2             26  16500.0        16500.0            2.0
3             30  13950.0        13950.0            4.0
4             22  17450.0        17450.0            4.0
..           ...      ...            ...            ...
200           28  16845.0        16845.0            4.0
201           25  19045.0        19045.0            4.0
202           23  21485.0        21485.0            4.0
203           27  22470.0        22470.0            4.0
204           25  22625.0        22625.0            4.0

[205 rows x 28 columns]

# <b>Problem 11 : Concatenate the two data frames given below firstly row wise and secondly column wise.</b>

<code>GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}</code>

<code>japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}</code>

In [ ]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}

japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
# Your code here


df_german = pd.DataFrame(GermanCars)
df_japanese = pd.DataFrame(japaneseCars)

concatenated_row_wise = pd.concat([df_german, df_japanese], ignore_index=True)
concatenated_column_wise = pd.concat([df_german, df_japanese], axis=1)

print("Concatenated Row-Wise:\n",concatenated_row_wise)
print("\nConcatenated Column-Wise:\n",concatenated_column_wise)

Concatenated Row-Wise:
        Company   Price
0         Ford   23845
1     Mercedes  171995
2          BMV  135925
3         Audi   71400
4       Toyota   29995
5        Honda   23600
6       Nissan   61500
7  Mitsubishi    58900

Concatenated Column-Wise:
     Company   Price      Company  Price
0      Ford   23845       Toyota  29995
1  Mercedes  171995        Honda  23600
2       BMV  135925       Nissan  61500
3      Audi   71400  Mitsubishi   58900